/** Generated by Deploy Gilbert Guide — source: pages-config.defaults.js. */
window.PAV_PICKER_CONFIG = {
  webhookUrl: "https://script.google.com/macros/s/AKfycbyXinGO9Tnh0XlI9pKRD2sp7z3ruY6ZvFZU3yIjtxMW2HTRyak94q1g7ixbFA2DTfiAXw/exec",
  depositAmount: 2500,
  quickbooksDepositUrl: "https://script.google.com/macros/s/AKfycbyXinGO9Tnh0XlI9pKRD2sp7z3ruY6ZvFZU3yIjtxMW2HTRyak94q1g7ixbFA2DTfiAXw/exec",
  notifyEmail: "support@gildedgooselimited.com"
};
